### ISSUE TITLE
RuntimeError: Failed to process string with tex because latex could not be found

### ISSUE THREAD

**Issue by zhangxin0611** [garrettj403/SciencePlots#13]
Runing enviroment Ubuntu 18.04
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> x = np.array(range(10))
>>> y = 3*x+5
>>> plt.plot(x,y)
[<matplotlib.lines.Line2D object at 0x7feefd5c2590>]
>>> plt.show() # show correctly
>>> plt.style.use('science')
>>> plt.plot(x,y)
[<matplotlib.lines.Line2D object at 0x7feef4ea1b10>]
>>> plt.show()
Traceback (most recent call last):
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/texmanager.py", line 304, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/home/zx/anaconda3/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/zx/anaconda3/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/zx/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/zx/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 505, in _draw_idle
    self.draw()
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/axis.py", line 1205, in draw
    renderer)
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/axis.py", line 1150, in _get_tick_bboxes
    for tick in ticks if tick.label1.get_visible()],
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/axis.py", line 1150, in <listcomp>
    for tick in ticks if tick.label1.get_visible()],
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/text.py", line 890, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/text.py", line 291, in _get_layout
    ismath="TeX" if self.get_usetex() else False)
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 201, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/texmanager.py", line 448, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/texmanager.py", line 338, in make_dvi
    texfile], tex)
  File "/home/zx/anaconda3/lib/python3.7/site-packages/matplotlib/texmanager.py", line 308, in _run_checked_subprocess
    'found'.format(command[0])) from exc
RuntimeError: Failed to process string with tex because latex could not be found

**Comment by garrettj403** [comment]
``SciencePlots`` uses Latex for font rendering. If you don't have Latex on your computer (and you don't want to download it), you can disable Latex using:
```python
plt.style.use(['science', 'no-latex'])
```

**Comment by zhangxin0611** [comment]
@garrettj403 Yes, Thanks. I solved the problem after installing Latex. Run the command `sudo apt-get install texlive-full` in the terminal.
