### ISSUE TITLE
Error because of comma between LaTeX package definitions

### ISSUE THREAD

**Issue by kurhar** [garrettj403/SciencePlots#4]
I get the following error if the comma is present in the marked line, if I remove the comma, it seems to work properly. The temporary files in the matplotlib cache directory also differ. Instead of `$1.0$` the combination `lp` appears. Strange.

https://github.com/garrettj403/SciencePlots/blob/17c9636fc1d77a3dfca763ef360b0adcc3fdf313/styles/science.mplstyle#L45

> With comma:

```latex
\documentclass{article}
\usepackage{type1cm}
\usepackage{textcomp}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}, \usepackage[T1]{fontenc}
\usepackage[papersize={72in,72in},body={70in,70in},margin={1in,1in}]{geometry}
\pagestyle{empty}
\begin{document}
\fontsize{10.000000}{12.500000}{\rmfamily lp}
\end{document}
```

> Without comma:
```latex
\documentclass{article}
\usepackage{type1cm}
\usepackage{textcomp}
\usepackage[utf8]{inputenc}
\usepackage{amsmath} \usepackage[T1]{fontenc}
\usepackage[papersize={72in,72in},body={70in,70in},margin={1in,1in}]{geometry}
\pagestyle{empty}
\begin{document}
\fontsize{10.000000}{12.500000}{\rmfamily $1.0$}
\end{document}
```

```python
sys.platform # 'win32'
sys.version #'3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]'
mpl.__version__#'3.1.0'
```

```python
plt.style.use("science")
xx = np.linspace(0, 2*np.pi, 1000)    
yy = np.sin(xx)
plt.plot(xx,yy)
[<matplotlib.lines.Line2D at 0x1f150e89988>]

Traceback (most recent call last):
  File "$anon_dir$\lib\site-packages\matplotlib\texmanager.py", line 304, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "$anon_dir$\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "$anon_dir$\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['latex', '-interaction=nonstopmode', '--halt-on-error', 'C:\\Users\\username\\.matplotlib\\tex.cache\\f257b68706cc7f7375bc4f24a206f94f.tex']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "$anon_dir$\lib\site-packages\matplotlib\backends\backend_qt5.py", line 501, in _draw_idle
    self.draw()
  File "$anon_dir$\lib\site-packages\matplotlib\backends\backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "$anon_dir$\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "$anon_dir$\lib\site-packages\matplotlib\figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "$anon_dir$\lib\site-packages\matplotlib\image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "$anon_dir$\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "$anon_dir$\lib\site-packages\matplotlib\axes\_base.py", line 2645, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "$anon_dir$\lib\site-packages\matplotlib\image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "$anon_dir$\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "$anon_dir$\lib\site-packages\matplotlib\axis.py", line 1206, in draw
    renderer)
  File "$anon_dir$\lib\site-packages\matplotlib\axis.py", line 1151, in _get_tick_bboxes
    for tick in ticks if tick.label1.get_visible()],
  File "$anon_dir$\lib\site-packages\matplotlib\axis.py", line 1151, in <listcomp>
    for tick in ticks if tick.label1.get_visible()],
  File "$anon_dir$\lib\site-packages\matplotlib\text.py", line 890, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "$anon_dir$\lib\site-packages\matplotlib\text.py", line 291, in _get_layout
    ismath="TeX" if self.get_usetex() else False)
  File "$anon_dir$\lib\site-packages\matplotlib\backends\backend_agg.py", line 201, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "$anon_dir$\lib\site-packages\matplotlib\texmanager.py", line 448, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "$anon_dir$\lib\site-packages\matplotlib\texmanager.py", line 338, in make_dvi
    texfile], tex)
  File "$anon_dir$\lib\site-packages\matplotlib\texmanager.py", line 317, in _run_checked_subprocess
    exc=exc.output.decode('utf-8'))) from exc
RuntimeError: latex was not able to process the following string:
b'lp'

Here is the full report generated by latex:
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6500 64-bit)
entering extended mode
(C:/Users/username/.matplotlib/tex.cache/f257b68706cc7f7375bc4f24a206f94f.tex
LaTeX2e <2017-04-15>
Babel <3.15> and hyphenation patterns for 75 language(s) loaded.
("C:\Program Files\MiKTeX 2.9\tex\latex\base\article.cls"
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
("C:\Program Files\MiKTeX 2.9\tex\latex\base\size10.clo"))
(C:\Users\username\AppData\Roaming\MiKTeX\2.9\tex\latex\type1cm\type1cm.sty)
("C:\Program Files\MiKTeX 2.9\tex\latex\base\textcomp.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\base\ts1enc.def"))
("C:\Program Files\MiKTeX 2.9\tex\latex\base\inputenc.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\base\utf8.def"
("C:\Program Files\MiKTeX 2.9\tex\latex\base\t1enc.dfu")
("C:\Program Files\MiKTeX 2.9\tex\latex\base\ot1enc.dfu")
("C:\Program Files\MiKTeX 2.9\tex\latex\base\omsenc.dfu")
("C:\Program Files\MiKTeX 2.9\tex\latex\base\ts1enc.dfu")))
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsmath.sty"
For additional information on amsmath, use the `?' option.
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amstext.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsgen.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsbsy.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsopn.sty"))

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.10 \usepackage{amsmath},
                           \usepackage[T1]{fontenc}
No pages of output.
Transcript written on f257b68706cc7f7375bc4f24a206f94f.log.

```

**Comment by garrettj403** [comment]
Hi @kurhar 

Thanks for bringing this up. For whatever reason, the ``fontenc`` package is causing some issues. This LaTeX package is only used to add 8-bit font encoding:

> The default font encoding (OT1) of TeX is 7-bit and uses fonts that have 128 glyphs, and so do not include the accented characters as individual glyphs. So a letter ö is made by adding an accent to the existing 'o' glyph. The T1 font encoding is an 8-bit encoding and uses fonts that have 256 glyphs. So an 'ö' is an actual single glyph in the font. ([source](https://tex.stackexchange.com/questions/664/why-should-i-use-usepackaget1fontenc))

I don't think that this package is necessary for SciencePlots, so I have removed it now in the latest commit.

**Comment by kurhar** [comment]
Thanks for looking into it. As far as I understand it should still work with charachters like ö, with the addition that hyphenation would be broken, but that does not matter in this case, as labels are short.
