### ISSUE TITLE
fail to use the science style

### ISSUE THREAD

**Issue by WX-github-maker** [garrettj403/SciencePlots#5]
I tried to use the science style which i had put it in C:\Users\****\.matplotlib\stylelib but failed.
Traceback (most recent call last):
  File "D:\Software\Anaconda3\lib\site-packages\matplotlib\texmanager.py", line 304, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "D:\Software\Anaconda3\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "D:\Software\Anaconda3\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:     
  File "D:\Software\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "D:\Software\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件

I am thinking about if I need to install Tex first and then I will fix it. Thank you.

**Comment by garrettj403** [comment]
You normally need LaTeX, but you can disable this by using:
```python
plt.style.use('science', 'no-latex')`
```

I haven't tried this on Windows, so you might have to put the style files in a different folder. What does this give you?
```python
import matplotlib
print(matplotlib.get_configdir())
```

**Comment by WX-github-maker** [comment]
Thanks for your advice. I have solvede it through downloading Tex. And I really appreciate your work while I am kooking for scientific style.
