### ISSUE TITLE
raise CalledProcessError, 

### ISSUE THREAD

**Issue by kalkite** [garrettj403/SciencePlots#90]
### Environment

```Python console
OS: Pop!_OS 22.04 LTS x86_64 
CPU: 11th Gen Intel i5-1135G7 (8) @ 4.200GHz 
Python 3.9.16
SciencePlots==2.0.1
matplotlib==3.5.3
matplotlib-inline==0.1.6
```

### Describe your issue here

Traceback (most recent call last):
  packages/matplotlib/texmanager.py", line 233, in _run_checked_subprocess
    report = subprocess.check_output(
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['latex', '-interaction=nonstopmode', '--halt-on-error', '../b0aabcb4234198774813facb0be0d0b8.tex']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-70383d4534a1>", line 20, in <module>
    fig.savefig('fig1.pdf')
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/figure.py", line 3058, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2295, in print_figure
    self.figure.draw(renderer)
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/figure.py", line 2845, in draw
    mimage._draw_list_compositing_images(
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3091, in draw
    mimage._draw_list_compositing_images(
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/axis.py", line 1159, in draw
    ticklabelBoxes, ticklabelBoxes2 = self._get_tick_bboxes(ticks_to_draw,
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/axis.py", line 1085, in _get_tick_bboxes
    return ([tick.label1.get_window_extent(renderer)
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/axis.py", line 1085, in <listcomp>
    return ([tick.label1.get_window_extent(renderer)
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/text.py", line 910, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/text.py", line 309, in _get_layout
    _, lp_h, lp_d = renderer.get_text_width_height_descent(
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/backends/_backend_pdf_ps.py", line 107, in get_text_width_height_descent
    w, h, d = texmanager.get_text_width_height_descent(
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/texmanager.py", line 335, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/texmanager.py", line 271, in make_dvi
    self._run_checked_subprocess(
  File "/home/rajeshkalakoti/PycharmProjects/iot_botnet_xai/venv/lib/python3.9/site-packages/matplotlib/texmanager.py", line 241, in _run_checked_subprocess
    raise RuntimeError(
RuntimeError: latex was not able to process the following string:
b'lp'
Here is the full report generated by latex:
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(../b0aabcb4234198774813facb0be0d0b8.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-01-21>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/type1cm/type1cm.sty)

### How can we reproduce it? What have you tried?

I attempted to use the code example from your repository at https://github.com/garrettj403/SciencePlots/blob/master/examples/plot-examples.py, but encountered the error mentioned above.

**Comment by garrettj403** [comment]
I'll assume this worked. Feel free to reopen.

**Comment by kalkite** [comment]
@garrettj403, it helped. Thank you very much.
